-- DLI sql
-- ******************************************************************** --
-- author: chenzhigao
-- create time: 2025/05/23 14:48:00 GMT+08:00
-- ******************************************************************** --
-- 专场商品详情表
INSERT OVERWRITE TABLE yishou_data.dwm_goods_sp_up_info_dt PARTITION (dt)
SELECT
    special_period
	, special_id
	, special_type
	, special_date
	, goods_id
	, goods_name
	, style
	, is_new
	, is_valid_new
	, is_supply_up
	, is_live
	, supply_id
	, supply_name
	, is_ka
	, 15day_up_supply
	, 15day_live_supply
	, special_buy_level
	, brand_id
	, master_brande_name
	, pg_id
	, pg_code
	, pg_name
	, pgm_code
	, pgm_name
	, goods_no
	, big_market
	, primary_market_name
	, second_market_name
	, primary_cat_name
	, second_cat_name
	, third_cat_name
	, grade_name
	, price_section
	, salenum_type
	, market_price
	, shop_price
	, buy_num
	, buy_amount
	, buy_user_num
	, real_buy_user_num
	, brand_name
	, is_supply_first_up
	, is_strength
	, style_names
	, is_self_supply
	, goods_exposure_uv
	, goods_exposure_pv
	, goods_detail_uv
	, goods_detail_pv
	, add_cart_uv
	, add_cart_pv
	, add_cart_num
	, add_cart_amount
	, real_buy_num
	, real_buy_amount
	, create_num
	, allot_24_num
	, allot_num
	, market_city
	, goods_season
	, is_in_stock
	, is_bargain
	, goods_status
	, is_on_sale
	, putaway_channel
	, old_putaway_channel
	, first_up_time
	, allot_48_num
	, allot_72_num
	, allot_96_num
	, allot_120_num
	, allot_240_num
	, is_b_port_100uv
	, is_b_port_100pay
	, is_b_port_baokuan
	, origin
	, is_platform
	, pre_discount_price
	, goods_first_up_time
	, last_up_time
	, first_up_new_martek_price
	, first_up_new_shop_price
	, up_type
	, goods_style_name
	, department
	, h5_goods_exposure_pv
	, h5_goods_exposure_uv
	, new_first_up_15d_buy_amount
	, new_first_up_15d_buy_num
	, new_first_up_15d_order_num
	, new_first_up_15d_pay_uv
	, new_first_up_15d_rebuy_uv
	, new_first_up_15d_rebuy_rate
	, is_quality_goods
	, is_children_quality_supply
	, is_quality_supply
	, supply_level
	, one_hand
	, special_name
	, special_style_type_name
	, resource_type
	, kol_class
	, is_bk
	, allot_24_amount
	, allot_48_amount
	, allot_72_amount
	, allot_96_amount
	, allot_120_amount
	, allot_240_amount
	, allot_final_amount
	, billing_amount
	, allot_final_num
	, allot_amount
	, allot_360_num
	, allot_360_amount
	, real_new_first_up_15d_buy_amount
	, real_new_first_up_15d_buy_num
	, real_new_first_up_15d_order_num
	, real_new_first_up_15d_pay_uv
	, real_new_first_up_15d_rebuy_uv
	, real_new_first_up_15d_rebuy_rate
	, real_special_buy_level
	, real_salenum_type
	, real_is_bk
	, first_depreciate
	, is_platform_with_sfr
	, vendor_supply_id
    , vendor_supply_name
    , goods_tier
    , admin_name
    , is_combination_buy
    , goods_level
    , goods_no_admin_name
    , create_amount
	, dt
FROM yishou_data.dws_goods_id_action_statistics_incr_dt
WHERE dt BETWEEN to_char(dateadd(to_date1('${start}', 'yyyymmdd'), -89, 'dd'), 'yyyymmdd') AND '${end}'
DISTRIBUTE BY dt
;