-- DLI sql
-- ******************************************************************** --
-- author: chenzhigao
-- create time: 2025/05/23 14:55:12 GMT+08:00
-- ******************************************************************** --
--
INSERT OVERWRITE TABLE yishou_data.dws_goods_id_action_statistics_incr_dt PARTITION (dt)
SELECT
    t1.special_period, --专场期数
    t1.special_id, --专场id
    t1.special_type, --专场类型风格
    t1.special_date, --专场日期
    t1.goods_id, --商品id
    t1.goods_name, --商品名称
    t1.style, --商品风格
    t1.is_new, --是否新款{1:是,0:否}
    t1.is_valid_new, --是否有效新款{1:是,0:否}
    t1.is_supply_up, --是否供应商自主上款{1:是,0:否}
    t1.is_live, --是否直播商品的款{1:是,0:否}
    t1.supply_id, --供应商ID
    t1.supply_name, --供应商名称
    t1.is_ka, --是否KA供应商{1:是,0:否}
    t1.15day_up_supply, --是否自主上新供应商 {1:是,0:否} (最近15天内有过自主上新)
    t1.15day_live_supply, --是否直播供应商 {1:是,0:否}(最近15天内有过直播)
    t1.special_buy_level, --供应商上月销售等级 {1S:[100万,+),2A:[50万，100万),3B:[30万,50万),4C:[10万,30万),5D:[5万,10万),6E:(0,5万),7F:0}
    t1.brand_id, --供应商主品牌ID
    t1.master_brande_name, --主品牌名称
    t1.pg_id, --买手组id
    t1.pg_code, --买手组代号
    t1.pg_name, --买手组名称
    t1.pgm_code, --买手代号
    t1.pgm_name, --买手姓名
    t1.goods_no, --商品货号
    t1.big_market, --大市场名称
    t1.primary_market_name, --一级市场名
    t1.second_market_name, --二级市场名
    t1.primary_cat_name, --一级品类名称
    t1.second_cat_name, --二级品类名称
    t1.third_cat_name, --三级品类名称
    t1.grade_name, --商品档次 {低档,中低档,中档,中高档,高档}
    t1.price_section, --销售价格带{共12个区间，划分区间详情参考数据字典}
    t1.salenum_type, --爆涨平滞(每日正价商品的货号对销售件数求和，并按照市场规则进行判断爆涨平滞)
    t1.market_price, --拿货价
    t1.shop_price, --销售价
    t1.buy_num, --销售件数
    t1.buy_amount, --销售额
    t1.buy_user_num, --支付用户数
    t1.real_buy_user_num, --实际支付用户数
    t1.brand_name, --品牌名称
    t1.is_supply_first_up, --是否供应商首次自主上款{1:是,0:否}
    t1.is_strength, --是否实力档口{1:是,0:否}
    t1.style_names, --供应商风格字符串版本
    t1.is_self_supply, --是否自主上款供应商{1:是,0:否}
    gi.goods_exposure_uv, --h5商品曝光uv+商品曝光UV
    gi.goods_exposure_pv, --h5商品曝光pv+商品曝光PV
    t1.goods_detail_uv, --商品点击UV
    t1.goods_detail_pv, --商品点击PV
    t1.add_cart_uv, --商品加购UV
    t1.add_cart_pv, --商品加购PV
    t1.add_cart_num, --商品加购件数
    t1.add_cart_amount, --商品加购金额
    t1.real_buy_num, --实际销售件数
    t1.real_buy_amount, --实际销售额
    t1.create_num, --应开单件数
    t1.allot_24_num, --24小时配货件数
    t1.allot_num, --配货件数
    t1.market_city, --市场所属城市
    t1.goods_season, --商品季节
    t1.is_in_stock, --是否现货{1:是,0:否}
    t1.is_bargain, --是否特价{1:是,0:否}
    t1.goods_status, --是否断货的款（正常/断货）
    t1.is_on_sale, --是否上架的款{1:上架,0:下架}
    t1.putaway_channel, --上架渠道
    t1.old_putaway_channel, --旧款上架渠道
    t1.first_up_time, --供应商首次上架时间
    t1.allot_48_num, --48小时配货件数
    t1.allot_72_num, --72小时配货件数
    t1.allot_96_num, --96小时配货件数
    t1.allot_120_num, --120小时配货件数
    t1.allot_240_num, --240小时配货件数
    t1.is_b_port_100uv, --0
    t1.is_b_port_100pay, --0
    t1.is_b_port_baokuan, --0
    t1.origin, --发货地
    t1.is_platform, --是否平台化供应商{0:否,1:是},刷数当天的状态且没限制无理由退货时间大于0
    t1.pre_discount_price, --折前价
    t1.goods_first_up_time, --商品首次上架时间
    t1.last_up_time, --商品最后一次上架时间
    t1.first_up_new_martek_price, --首次上新商品对应拿货价
    t1.first_up_new_shop_price, --首次上新商品对应售价
    t1.up_type, --上架方式
    t1.goods_style_name, --新风格名称（goods_style对应的名称）
    t1.department, --供给部门
    gi.h5_goods_exposure_pv, --h5页商品列表曝光pv
    gi.h5_goods_exposure_uv, --h5页商品列表曝光uv
    t1.new_first_up_15d_buy_amount, --商品新款首次上架15天内销售额
    t1.new_first_up_15d_buy_num, --商品新款首次上架15天内销售件数
    t1.new_first_up_15d_order_num, --商品新款首次上架15天内销售订单数
    t1.new_first_up_15d_pay_uv, --上新15天内支付用户
    t1.new_first_up_15d_rebuy_uv, --上新15天内签收后复购用户
    t1.new_first_up_15d_rebuy_rate, --商品新款首次上架15天内复购返单率
    t1.is_quality_goods, --是否为优质商品
    t1.is_children_quality_supply, --是否童装部的优质商家
    t1.is_quality_supply, --是否为优质商家
    t1.supply_level, --S,A,B,C,D等级
    t1.one_hand, --是否一手拿{0否 1是}
    t1.special_name, --专场名称
    t1.special_style_type_name, --专场风格类型对应中文名
    t1.resource_type, --资源类型（1模特图2实拍图3短视频
    t1.kol_class, --kol品牌系列分类
    t1.is_bk, --是否爆款{1:是,0:否}（商品id当天销售件数>15件记为爆款）
    t1.allot_24_amount, --24小时配货金额
    t1.allot_48_amount, --48小时配货金额
    t1.allot_72_amount, --72小时配货金额
    t1.allot_96_amount, --96小时配货金额
    t1.allot_120_amount, --120小时配货金额
    t1.allot_240_amount, --240小时配货金额
    t1.allot_final_amount, --最终配货金额
    t1.billing_amount, --应开单金额
    t1.allot_final_num, --最终配货件数
    t1.allot_amount, --配货金额
    t1.allot_360_num, --360小时配货件数
    t1.allot_360_amount, --360小时配货金额
    t1.real_new_first_up_15d_buy_amount, --商品新款首次上架15天内实际销售额
    t1.real_new_first_up_15d_buy_num, --商品新款首次上架15天内实际销售件数
    t1.real_new_first_up_15d_order_num, --商品新款首次上架15天内实际销售订单数
    t1.real_new_first_up_15d_pay_uv, --上新15天内实际支付用户
    t1.real_new_first_up_15d_rebuy_uv, --上新15天内签收后实际复购用户
    t1.real_new_first_up_15d_rebuy_rate, --商品新款首次上架15天内实际复购返单率
    t1.real_special_buy_level, --销售等级{S:[100万,+),A:[50万，100万),B:[30万,50万),C:[10万,30万),D:[5万,10万),E:(0,5万),F:0
    t1.real_salenum_type, --用真实支付计算的爆涨平滞(每日正价商品的货号对销售件数求和，并按照市场规则进行判断爆涨平滞)
    t1.real_is_bk, --用真实支付计算的是否爆款
    t1.first_depreciate, --是否首次降价
    t1.market_id, --市场id
    t1.market_name, --市场名称
    t1.primary_cat_id, --一级品类id
    t1.second_cat_id, --二级品类id
    t1.third_cat_id, --三级品类id
    t1.supply_lm_sale_level, --供应商上月销售等级
    t1.picker_group_code, --买手代号
    t1.picker_group, --买手组id
    t1.is_three_sale, --是否三件动销{1:是,0:否}（商品id当天销售件数>=3件记为三件动销）
    t1.is_day_up, --当天是否上架
    t1.special_start_time, --专场开始时间
    t1.is_supply_up_new_supply_15d, --是否自主上新供应商(最近15天内有过自主上新)
    t1.is_live_supply_15d, --是否直播供应商(最近15天内有过直播)
    t1.primary_market_id, --一级市场id
    t1.second_market_id, --二级市场id
    t1.pay_user_num, --支付用户数
    t1.real_pay_user_num, --实际支付用户数
    gi.goods_exposure_uv_without_h5, --商品曝光UV_不含h5
    gi.goods_exposure_pv_without_h5, --商品曝光PV_不含h5
    t1.goods_click_uv, --商品点击UV
    t1.goods_click_pv, --商品点击PV
    t1.goods_add_cart_uv, --商品加购UV
    t1.goods_add_cart_pv, --商品加购PV
    t1.goods_add_cart_num, --商品加购件数
    t1.goods_add_cart_amount, --商品加购金额
    t1.invitation_in, --邀约供应商入驻入口{0:关闭,1:开启}
    t1.open_deposit, --保证金入口{0:关闭,1:开启}
    t1.pay_method, --支付方式:{1:转账,2:分账}
    t1.self_set_sole, --自主设置一手独家款:{0:否, 1:是}
    t1.no_reason_return, --供应商是否支持无理由退换:{0:否,1:是}
    t1.refund_model, --退货模式:{1:退货由一手处理,2:退货由商家处理}
    t1.refund_member_id, --退供员id对应defective_group_member的dg_member_id
    t1.sepcial_buy_amount, --销售额
    t1.special_real_amount, --实际销售额
    t1.up_new_num, --上架新款数
    t1.move_new_num, --动销新款数
    t1.add_fans, --新增粉丝数
    t1.pay_rebuy_rate, --30日复购率
    t1.new_level, --新层级
    t1.putaway_type, --上架方式（用户主动补货、人工上架、阿尔法上架）
    t1.sales, --商品总销售数量
    t1.enough_number, --成团数量
    t1.b_port_buy_amount, --B端GMV
    t1.real_move_new_num, --动销新款数
    t1.real_pay_rebuy_rate, --30天复购率
    t1.real_new_level, --新等级
    t1.real_b_port_buy_amount, --B端GMV
    t1.current_security_amount, --已交保证金金额
    t1.need_security_amount, --需要保证金金额
    t1.balance, --可提现金额
    t1.create_time, --创建时间
    t1.update_time, --更新时间
    t1.wx_picture, --微信联系二维码
    t1.wx_no, --微信号
    t1.platform_security_amount, --入驻平台化保证金
    t1.platform_year_amount, --平台化年费
    t1.no_reason_begin_time, --退货服务开始时间
    t1.special_show, --是否展示
    t1.goods_kh, --商品款号
    t1.supplier_id, --档口id
    t1.picker_assist, --买辅代号列表
    t1.pgid, --采购ID
    t1.cat_id, --类目ID
    t1.fabric_id, --面料表ID
    t1.origin_name, --发货地中文
    t1.allot_num_24h, --24小时配货件数
    t1.allot_num_48h, --48小时配货件数
    t1.allot_num_72h, --72小时配货件数
    t1.allot_num_96h, --96小时配货件数
    t1.allot_num_120h, --120小时配货件数
    t1.allot_num_240h, --240小时配货件数
    t1.shipped_num, --发货件数
    t1.shipped_num_24h, --24小时发货件数
    t1.shipped_num_48h, --48小时发货件数
    t1.shipped_num_72h, --72小时发货件数
    t1.shipped_num_96h, --96小时发货件数
    t1.shipped_num_120h, --120小时发货件数
    t1.shipped_num_168h, --168小时发货件数
    t1.signed_num_24h, --24小时签收件数
    t1.signed_num_48h, --48小时签收件数
    t1.signed_num_72h, --72小时签收件数
    t1.signed_num_96h, --96小时签收件数
    t1.signed_num_120h, --120小时签收件数
    t1.signed_num_168h, --168小时签收件数
    t1.signed_num_total, --最终签收件数
    t1.stock_in_num, --入库件数
    t1.work_stock_in_num, --售后入库件数
    t1.qzc_stock_in_num, --前置仓入库件数
    t1.create_amount, --应开单金额
    t1.allot_amount_24h, --24小时配货金额
    t1.allot_amount_48h, --48小时配货金额
    t1.allot_amount_72h, --72小时配货金额
    t1.allot_amount_96h, --96小时配货金额
    t1.allot_amount_120h, --120小时配货金额
    t1.allot_amount_240h, --24小时配货金额
    t1.shipped_amount, --发货金额
    t1.shipped_amount_24h, --24小时发货金额
    t1.shipped_amount_48h, --48小时发货金额
    t1.shipped_amount_72h, --72小时发货金额
    t1.shipped_amount_96h, --96小时发货金额
    t1.shipped_amount_120h, --120小时发货金额
    t1.shipped_amount_168h, --168小时发货金额
    t1.signed_amount_24h, --24小时签收金额
    t1.signed_amount_48h, --48小时签收金额
    t1.signed_amount_72h, --72小时签收金额
    t1.signed_amount_96h, --96小时签收金额
    t1.signed_amount_120h, --120小时签收金额
    t1.signed_amount_168h, --168小时签收金额
    t1.signed_amount_total, --最终签收金额
    t1.stock_in_amount, --入库金额
    t1.work_stock_in_amount, --售后入库金额
    t1.qzc_stock_in_amount, --前置仓入库金额
    t1.is_24h_shipped_num, --24h发标签发货件数
    t1.is_24h_shipped_amount, --24h发标签发货金额
    t1.refund_goods_number, --退货件数
    t1.refund_goods_money, --退货金额
    t1.no_reason_goods_number, --无理由退货件数
    t1.no_reason_refund_goods_money, --无理由退货金额
    t1.comments_num, --评价数
    t1.comments_user_num, --评价人数
    t1.total_score, --评价总分
    t1.highest_score, --评价最高分
    t1.lowest_score, --评价最低分
    t1.bad_num, --次品件数
    t1.bad_amount, --次品金额
    t1.bad_20d_num, --不良品数量
    t1.dispatch_num, --20天前那天下单数量
    t1.order_100_no_reason_refund_num, --订单维度100%无理由退货件数
    t1.order_100_no_reason_refund_money, --订单维度100%无理由退货金额
    t1.order_worry_free_refund_num, --订单维度无忧退退货件数
    t1.order_worry_free_refund_money, --订单维度无忧退退货金额
    t1.order_big_brand_refund_num, --订单维度大牌无忧退货件数
    t1.order_big_brand_refund_money, --订单维度大牌无忧退货金额
    t1.so_100_no_reason_refund_num, --工单维度100%无理由退货件数
    t1.so_100_no_reason_refund_money, --工单维度100%无理由退货金额
    t1.so_worry_free_refund_num, --工单维度无忧退退货件数
    t1.so_worry_free_refund_money, --工单维度无忧退退货金额
    t1.so_big_brand_refund_num, --工单维度大牌无忧退货件数
    t1.so_big_brand_refund_money, --工单维度大牌无忧退货金额
    t1.wait_allot_num, --待配货件数（配货状态为待配货或排单,购买件数-配货件数-退货件数）
    t1.waiting_num, --正在排单件数（配货状态为排单,购买件数-配货件数-退货件数）
    t1.stock_num_total, --最终断货件数
    t1.shipped_amount_100_no_reason, --100%无理由发货金额
    t1.shipped_num_100_no_reason, --100%无理由发货件数
    t1.shipped_amount_worry_free, --无忧退发货金额
    t1.shipped_num_worry_free, --无忧退发货件数
    t1.shipped_amount_big_brand, --大牌无忧发货金额
    t1.shipped_num_big_brand, --大牌无忧发货件数
    t1.allot_num_360h, --15天配货件数
    t1.signed_num_240h, --15天签收件数
    t1.signed_num_360h, --15天签收件数
    t1.shipped_num_240h, --15天发货件数
    t1.shipped_num_360h, --15天发货件数
    t1.allot_amount_360h, --15天配货金额
    t1.is_platform_with_sfr, --是否平台化_收取佣金
    t1.vendor_supply_id, --渠道供应商ID
    t1.vendor_supply_name, --渠道供应商名称
    t1.goods_tier, --商品分层
    t1.admin_name, --商品分层
    t1.is_combination_buy, --是否搭配购商品
    t1.goods_level, --商品动销等级_从明日新品出数
    t1.goods_no_admin_name, --商品款添加人, 从goods_lib表出
    t1.last_month_goods_no_gmv, --商品款上月gmv
    t1.cur_month_goods_no_gmv, --商品款当月gmv
    t1.first_up_new_time, --商品第一次上新时间（当商品提前上架后又取消的不算第一次上新）（专场开始时间）
    t1.real_tier_num, --阶梯价实际销量
    t1.real_tier_gmv, --阶梯价实际销售额
    t1.real_tier_percent, --阶梯价实际占比
    t1.dt --日期分区
FROM  dws_goods_id_action_statistics_incr_dt_backup t1
left join dws_goods_id_action_statistics_incr_dt_backup1 gi
on t1.goods_id = gi.goods_id
    and t1.special_date = gi.special_date
    and gi.dt BETWEEN 20241023 and 20250501
where t1.dt BETWEEN 20241023 and 20250501;