-- 全量表拉链表

-- 背景：需要对一个数据量很大的全量表以拉链表的形式提取出近2天的数据出来单独放一张表

-- 建增量到oc表
-- CREATE EXTERNAL TABLE yishou_data.dim_goods_id_info_to_oc (
--  `goods_id` bigint  COMMENT '商品id',
--   `goods_name` string  COMMENT '商品名字',
--   `goods_no` bigint  COMMENT '商品货号',
--   `goods_img` string  COMMENT '商品图片',
--   `special_id` bigint  COMMENT '专场id',
--   `special_period` bigint  COMMENT '专场期数',
--   `cat_id` bigint  COMMENT '品类id',
--   `brand_id` bigint  COMMENT '品牌id',
--   `supply_id` bigint  COMMENT '供应商id',
--   `market_id` bigint  COMMENT '市场id',
--   `pg_id` bigint  COMMENT '买手组id',
--   `pg_code` string  COMMENT '买手组代号',
--   `pg_name` string  COMMENT '买手组名称',
--   `pgm_code` string  COMMENT '买手代号',
--   `pgm_name` string  COMMENT '买手姓名',
--   `pgid` bigint  COMMENT '采购组id',
--   `goods_kh` string  COMMENT '款号',
--   `market_price` double  COMMENT '活动拿货价',
--   `shop_price` double  COMMENT '商品价格',
--   `level_shop_price` string  COMMENT '价格区间',
--   `special_start_time` string  COMMENT '专场开始时间',
--   `special_start_rank` bigint  COMMENT '上架顺序',
--   `is_video` bigint  COMMENT '是否小视频{1:是,0:否}',
--   `admin_name` string  COMMENT '上架人',
--   `putaway_type` string  COMMENT '上架方式:人工上架,用户主动补货,阿尔法上架',
--   `putaway_channel` string  COMMENT '上架渠道:现货上架,用户补货,正常上架{判断优先级:现货上架>用户补货>正常上架} ',
--   `add_time` string  COMMENT '商品添加时间',
--   `shoppe_discount` double  COMMENT '折扣',
--   `shoppe_price` double  COMMENT '专柜价【高于销售价】',
--   `alone_discount` double  COMMENT '一手币折扣',
--   `alone_price` double  COMMENT '一手币价格',
--   `original_price` double  COMMENT '销售原始价',
--   `is_bargain` bigint  COMMENT '是否特价{1:是,0:否}',
--   `is_new` bigint  COMMENT '是否新款{1:是,0:否}',
--   `is_supply_first_up` bigint  COMMENT '是否供应商首次自主上款{1:是,0:否}',
--   `is_supply_up` bigint  COMMENT '是否供应商自主上款{1:是,0:否}',
--   `is_in_stock` bigint  COMMENT '是否现货{1:是,0:否}',
--   `is_today_first_live` bigint  COMMENT '是否当天首次直播{1:是,0:否}',
--   `is_live` bigint  COMMENT '是否直播商品（商品款直播过，以后的商品id都记为直播商品）{1:是,0:否}',
--   `is_today_live` bigint  COMMENT '是否当天直播款{1:是,0:否}',
--   `is_live_room` bigint  COMMENT '是否直播间开始时对应的商品id{1:是,0:否}',
--   `is_valid` bigint  COMMENT '是否有效{1:是,0:否}',
--   `origin` bigint  COMMENT '商品发货地',
--   `origin_name` string  COMMENT '商品发货地中文名称',
--   `grade` bigint  COMMENT '商品档次{1:高档,2:中高档,3:中档,4:中低档,5:低档,}',
--   `grade_name` string  COMMENT '商品档次中文:低档,中低档,中档,中高档,高档',
--   `special_date` string  COMMENT '专场日期',
--   `extra_price` double  COMMENT '加价',
--   `goods_type` bigint  COMMENT '商品类型{1:特价,}',
--   `sales` bigint  COMMENT '刷单销量',
--   `enough_number` bigint  COMMENT '成团数量',
--   `is_ext_new` bigint ,
--   `supply_name` string  COMMENT '供应商名称',
--   `old_price` double  COMMENT '原价',
--   `special_style_type` string  COMMENT '专场风格详情',
--   `special_name` string  COMMENT '专场名称',
--   `replenish_type` string  COMMENT '上架渠道'
-- ) COMMENT '商品维度表（增量到oc）' 
-- STORED AS ORC LOCATION 'obs://yishou-bigdata/yishou_data.db/dim_goods_id_info_to_oc'
-- ;

-- 新增字段
-- alter table yishou_data.dim_goods_id_info_to_oc 
-- add columns (
--     `update_time` STRING COMMENT '更新时间',
--     `special_show` BIGINT COMMENT '是否展示 {0:不展示,1:展示}',
--     `goods_no_admin_name` STRING COMMENT '商品库表的添加人姓名',
--     `purchaser_id` STRING COMMENT '采购组ID',
--     `purchaser_name` STRING COMMENT '采购组',
--     `purchaser_member_id` STRING COMMENT '采购员ID',
--     `purchaser_member_name` STRING COMMENT '采购员',
--     `dg_id` STRING COMMENT '次品组ID',
--     `dg_name` STRING COMMENT '次品组',
--     `dgm_id` STRING COMMENT '市场专场/次品专员ID',
--     `dgm_name` STRING COMMENT '市场专场/次品专员',
--     `follower_id` STRING COMMENT '商运ID',
--     `follower_name` STRING COMMENT '商运',
--     `vendor_supply_id` BIGINT COMMENT '渠道商ID',
--     `department` STRING COMMENT '部分',
--     `sub_department` STRING COMMENT '细分部门',
--     `comprhs_rank_level_mt` STRING COMMENT '商品力商家排名层级',
--     `last_month_sales_tier` STRING COMMENT '上月商家累计业绩排名层级',
--     `current_month_sales_tier` STRING COMMENT '当月商家累计业绩排名层级',
--     `salenum_type` STRING COMMENT '爆涨平滞',
--     `real_stock_num` BIGINT COMMENT '该货号当天实际库存',
--     `is_wide_stock` BIGINT COMMENT '是否广义现货, 1是0否',
--     `drawing_img` STRING COMMENT '版型图片',
--     `drawing_name` STRING COMMENT '版型名称',
--     `goods_rank_level` STRING COMMENT '商品排名等级',
--     `sale_age` BIGINT COMMENT '售龄'
-- ); 

insert overwrite table yishou_data.dim_goods_id_info_to_oc
select
    main_table.*
from yishou_data.dim_goods_id_info as main_table
inner join (
    select
        new_table.*
    from (
        -- 新增内容
        select
            goods_id,
            concat(coalesce(goods_id, ''),
            coalesce(goods_name, ''),
            coalesce(goods_no, ''),
            coalesce(goods_img, ''),
            coalesce(special_id, ''),
            coalesce(special_period, ''),
            coalesce(cat_id, ''),
            coalesce(brand_id, ''),
            coalesce(supply_id, ''),
            coalesce(market_id, ''),
            coalesce(pg_id, ''),
            coalesce(pg_code, ''),
            coalesce(pg_name, ''),
            coalesce(pgm_code, ''),
            coalesce(pgm_name, ''),
            coalesce(pgid, ''),
            coalesce(goods_kh, ''),
            coalesce(market_price, ''),
            coalesce(shop_price, ''),
            coalesce(level_shop_price, ''),
            coalesce(special_start_time, ''),
            coalesce(special_start_rank, ''),
            coalesce(is_video, ''),
            coalesce(admin_name, ''),
            coalesce(putaway_type, ''),
            coalesce(putaway_channel, ''),
            coalesce(add_time, ''),
            coalesce(shoppe_discount, ''),
            coalesce(shoppe_price, ''),
            coalesce(alone_discount, ''),
            coalesce(alone_price, ''),
            coalesce(original_price, ''),
            coalesce(is_bargain, ''),
            coalesce(is_new, ''),
            coalesce(is_supply_first_up, ''),
            coalesce(is_supply_up, ''),
            coalesce(is_in_stock, ''),
            coalesce(is_today_first_live, ''),
            coalesce(is_live, ''),
            coalesce(is_today_live, ''),
            coalesce(is_live_room, ''),
            coalesce(is_valid, ''),
            coalesce(origin, ''),
            coalesce(origin_name, ''),
            coalesce(grade, ''),
            coalesce(grade_name, ''),
            coalesce(special_date, ''),
            coalesce(extra_price, ''),
            coalesce(goods_type, ''),
            coalesce(sales, ''),
            coalesce(enough_number, ''),
            coalesce(is_ext_new, ''),
            coalesce(supply_name, ''),
            coalesce(old_price, ''),
            coalesce(special_style_type, ''),
            coalesce(special_name, ''),
            coalesce(replenish_type ,''),
            coalesce(update_time,''),''),
            coalesce(special_show,''),''), 
            coalesce(goods_no_admin_name,''), 
            coalesce(purchaser_id,''), 
            coalesce(purchaser_name,''), 
            coalesce(purchaser_member_id,''), 
            coalesce(purchaser_member_name,''), 
            coalesce(dg_id,''),
            coalesce(dg_name,''),
            coalesce(dgm_id,''), 
            coalesce(dgm_name,''), 
            coalesce(follower_id,''), 
            coalesce(follower_name,''), 
            coalesce(vendor_supply_id,''),
            coalesce(department,''), 
            coalesce(sub_department,''), 
            coalesce(comprhs_rank_level_mt,''),
            coalesce(last_month_sales_tier,''), 
            coalesce(current_month_sales_tier,''), 
            coalesce(salenum_type,''),
            coalesce(real_stock_num,''), 
            coalesce(is_wide_stock,''), 
            coalesce(drawing_img,''), 
            coalesce(drawing_name,''),
            coalesce(goods_rank_level,''), 
            coalesce(sale_age,'')) as new_content
        from yishou_data.dim_goods_id_info gi
    ) as new_table
    left join (
        -- 历史表，存放昨天的表
        select
            goods_id,
            concat(coalesce(goods_id, ''),
            coalesce(goods_name, ''),
            coalesce(goods_no, ''),
            coalesce(goods_img, ''),
            coalesce(special_id, ''),
            coalesce(special_period, ''),
            coalesce(cat_id, ''),
            coalesce(brand_id, ''),
            coalesce(supply_id, ''),
            coalesce(market_id, ''),
            coalesce(pg_id, ''),
            coalesce(pg_code, ''),
            coalesce(pg_name, ''),
            coalesce(pgm_code, ''),
            coalesce(pgm_name, ''),
            coalesce(pgid, ''),
            coalesce(goods_kh, ''),
            coalesce(market_price, ''),
            coalesce(shop_price, ''),
            coalesce(level_shop_price, ''),
            coalesce(special_start_time, ''),
            coalesce(special_start_rank, ''),
            coalesce(is_video, ''),
            coalesce(admin_name, ''),
            coalesce(putaway_type, ''),
            coalesce(putaway_channel, ''),
            coalesce(add_time, ''),
            coalesce(shoppe_discount, ''),
            coalesce(shoppe_price, ''),
            coalesce(alone_discount, ''),
            coalesce(alone_price, ''),
            coalesce(original_price, ''),
            coalesce(is_bargain, ''),
            coalesce(is_new, ''),
            coalesce(is_supply_first_up, ''),
            coalesce(is_supply_up, ''),
            coalesce(is_in_stock, ''),
            coalesce(is_today_first_live, ''),
            coalesce(is_live, ''),
            coalesce(is_today_live, ''),
            coalesce(is_live_room, ''),
            coalesce(is_valid, ''),
            coalesce(origin, ''),
            coalesce(origin_name, ''),
            coalesce(grade, ''),
            coalesce(grade_name, ''),
            coalesce(special_date, ''),
            coalesce(extra_price, ''),
            coalesce(goods_type, ''),
            coalesce(sales, ''),
            coalesce(enough_number, ''),
            coalesce(is_ext_new, ''),
            coalesce(supply_name, ''),
            coalesce(old_price, ''),
            coalesce(special_style_type, ''),
            coalesce(special_name, ''),
            coalesce(replenish_type ,'')) as history_content
        from yishou_data.dim_goods_id_info_history
    ) as history_table
    on new_table.goods_id = history_table.goods_id
    where new_table.new_content != history_table.history_content or coalesce(history_table.history_content, '') = ''
) as upsert_pk_table
on main_table.goods_id = upsert_pk_table.goods_id
DISTRIBUTE BY floor(rand()*100)
;
